package ECBEncryption;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


import static ECBEncryption.ECBEncryption.*;

public class ECBEncryptionGUI extends JFrame {
    private JTextField encryptText;
    private JTextField blockSize;
    private JPanel mainPanel;
    private JLabel textLabel;
    private JLabel blockSizeLabel;
    private JButton encrypt;
    private JButton decrypt;
    private JLabel resultLabel;

    public ECBEncryptionGUI() {
        setSize(500, 500);

        encrypt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String userInput = encryptText.getText().toUpperCase();
                if (isTextOkeGUI(userInput) && blockSize.getText().length() > 0 && userInput.length() > 0) {
                    if (isBlockSizeOkGUI(userInput, Integer.parseInt(blockSize.getText()))) {
                        String enc = encryptGUI(userInput, Integer.parseInt(blockSize.getText()));
                        resultLabel.setText(enc);
                    }
                }
            }
        });

        decrypt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String userInput = encryptText.getText().toUpperCase();
                if (isTextOkeGUI(userInput) && blockSize.getText().length() > 0 && userInput.length() > 0) {
                    if (isBlockSizeOkGUI(userInput, Integer.parseInt(blockSize.getText()))) {
                        String dec = decryptGUI(userInput, Integer.parseInt(blockSize.getText()));
                        resultLabel.setText(dec);
                    }
                }
            }
        });
    }

    public void runGUI() {
        JFrame frame = new JFrame("Entschlüsseln / Verschlüsseln");
        frame.setContentPane(new ECBEncryptionGUI().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public String decryptGUI(String text, int blockSize) {
        var textInBits = textToBits(text);
        var bitsToBlocks = bitsToBlocks(textInBits, blockSize);
        var blockShift = decryptBlocks(bitsToBlocks);
        var blockToBits = blocksToBits(blockShift);

        for (int i = 0; i < textInBits.length; i++) {
            if (i < blockToBits.length) {
                textInBits[i] = blockToBits[i];
            } else {
                break;
            }
        }

        var bitsToText = bitsToText(textInBits, symbolLenght());
        return new String(bitsToText);
    }

    public String encryptGUI(String text, int blockSize) {
        var textInBits = textToBits(text);
        var bitsToBlocks = bitsToBlocks(textInBits, blockSize);
        var blockShift = encryptBlocks(bitsToBlocks);
        var blockToBits = blocksToBits(blockShift);

        for (int i = 0; i < textInBits.length; i++) {
            if (i < blockToBits.length) {
                textInBits[i] = blockToBits[i];
            } else {
                break;
            }
        }

        var bitsToText = bitsToText(textInBits, symbolLenght());
        return new String(bitsToText);
    }

    public boolean isTextOkeGUI(String text) {
        for (int i = 0; i < text.length(); i++) {
            if (!encryptionCodeMap.containsKey(text.charAt(i))) {
                JOptionPane.showMessageDialog(
                        null,
                        "Der Buchstabe ( " + text.charAt(i) + " ) ist nicht erlaubt",
                        "Der Text enthält unzulassige Zeichen",
                        JOptionPane.ERROR_MESSAGE
                );
                return false;
            }
        }
        return true;
    }

    public boolean isBlockSizeOkGUI(String text, int blockSize) {
        int textLength = text.length() * symbolLenght();
        if (textLength < blockSize) {
            JOptionPane.showMessageDialog(
                    null,
                    "Blockgröße ist zu groß",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return false;
        }
        return true;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(5, 5, 5, 5), -1, -1));
        encrypt = new JButton();
        encrypt.setText("Verschlüsseln");
        mainPanel.add(encrypt, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        decrypt = new JButton();
        decrypt.setText("Entschlüsseln");
        mainPanel.add(decrypt, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        textLabel = new JLabel();
        textLabel.setText("Eingabefeld für den Zu Verschlüsselden Text");
        panel1.add(textLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        encryptText = new JTextField();
        panel1.add(encryptText, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        blockSizeLabel = new JLabel();
        blockSizeLabel.setText("Eingabefeld für die Block Größe");
        panel1.add(blockSizeLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        blockSize = new JTextField();
        panel1.add(blockSize, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        resultLabel = new JLabel();
        resultLabel.setText("-");
        mainPanel.add(resultLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textLabel.setLabelFor(encryptText);
        blockSizeLabel.setLabelFor(blockSize);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
